-- Migration: reconcile get_effective_config line endings
-- Generated by `supabase db diff` to align the DB with the declarative schema files.
-- The previous version of this function (migration 20260317000002) had CRLF line endings;
-- the schema files use LF. This migration makes the DB state match supabase/schemas/functions.sql.
-- Design reference: docs/design/lld-phase-2-web-auth-db.md §2.1 Declarative schema adoption
-- Issue: #65

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_effective_config(repo_id uuid)
 RETURNS TABLE(prcc_enabled boolean, fcs_enabled boolean, enforcement_mode text, score_threshold integer, prcc_question_count integer, fcs_question_count integer, min_pr_size integer, trivial_commit_threshold integer, exempt_file_patterns text[], context_file_patterns text[])
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  SELECT
    COALESCE(rc.prcc_enabled, oc.prcc_enabled),
    COALESCE(rc.fcs_enabled, oc.fcs_enabled),
    COALESCE(rc.enforcement_mode, oc.enforcement_mode),
    COALESCE(rc.score_threshold, oc.score_threshold),
    COALESCE(rc.prcc_question_count, oc.prcc_question_count),
    COALESCE(rc.fcs_question_count, oc.fcs_question_count),
    COALESCE(rc.min_pr_size, oc.min_pr_size),
    COALESCE(rc.trivial_commit_threshold, oc.trivial_commit_threshold),
    COALESCE(rc.exempt_file_patterns, oc.exempt_file_patterns),
    COALESCE(rc.context_file_patterns, oc.context_file_patterns)
  FROM repositories r
  JOIN org_config oc ON oc.org_id = r.org_id
  LEFT JOIN repository_config rc ON rc.repository_id = r.id
  WHERE r.id = repo_id
$function$
;


